name: Simple Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'releases/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.10
          name: Release v1.0.10
          files: releases/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
